app:
  image: feuyeux/spring-boot-docker
  links:
    - redis
  ports:
   - "18080:8080"
redis:
  image: index.tenxcloud.com/tenxcloud/redis
  environment:
   - REDIS_PASS=cache_me
  ports:
    - "16379:6379"