server:
  port: 8080

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: true
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: INFO

